name: Codacy Analysis

on: [push]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.4.5
